### PR TITLE
Prevent clients from reusing connections for proxy mode

### LINKED ISSUE #268: [BUG] Resolver proxy returns 403 for requests that reuses the same connection as the first request
### Bug description

When scaling up, KubeElasti resolver proxy only serves the first request in the first connection and then returns 403 for all subsequent requests in that connection. This makes any application that reuses connections to fail when they are triggering a scale up event (e.g. git http clones)

### Steps to reproduce

1. Install KubeElasti with any http service.
2. Wait for the ElastiService to scale down to 0
3. Open an in-cluster shell with `curl`: `kubectl run --rm -it --image docker.io/alpine/curl --command=true test -- /bin/sh`
4. Run `curl -vL http://<service-name>.<namespace> -o /dev/null http://<service-name>.<namespace> -o /dev/null`

### Expected behavior

The curl command returns whatever response the proxied http service backend is returning

### Actual behavior

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0   0     0   0     0     0     0  --:--:-- --:--:-- --:--:--     0* Host litellm-proxy.default:80 was resolved.
* IPv6: (none)
* IPv4: 10.102.167.54
*   Trying 10.102.167.54:80...
* Established connection to litellm-proxy.default (10.102.167.54 port 80) from 10.244.0.101 port 50554
* using HTTP/1.x
> GET / HTTP/1.1
> Host: litellm-proxy.default
> User-Agent: curl/8.17.0
> Accept: */*
>
* Request completely sent off
  0     0   0     0   0     0     0     0  --:--:--  0:00:06 --:--:--     0< HTTP/1.1 200 OK
< Content-Length: 835
< Content-Type: text/html; charset=utf-8
< Date: Mon, 13 Apr 2026 23:47:30 GMT
< Server: uvicorn
<
{ [835 bytes data]
100   835 100   835   0     0   138     0   0:00:06  0:00:06 --:--:--   208
* Connection #0 to host litellm-proxy.default:80 left intact
* Reusing existing http: connection with host litellm-proxy.default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0   0     0   0     0     0     0  --:--:-- --:--:-- --:--:--     0> GET / HTTP/1.1
> Host: litellm-proxy.default
> User-Agent: curl/8.17.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 403 Forbidden
< Connection: close
< Content-Type: application/json
< Date: Mon, 13 Apr 2026 23:47:30 GMT
< Content-Length: 32
<
{ [32 bytes data]
100    32 100    32   0     0 79404     0  --:--:-- --:--:-- --:--:-- 32000
* shutting down connection #0
```

The second request always gets a 403 response from KubeElasti.

### Kubernetes version

v1.35.1+k0s

### Elasti version

0.1.21

### Installation method

Helm

### Helm values or install overrides

```yaml
None
```

### External components in the request path

None

### Autoscaler in use

HPA

### Cloud provider (if applicable)

_No response_

### Logs and additional context

[Resolver handler logic](https://github.com/KubeElasti/KubeElasti/blob/main/resolver/internal/handler/handler.go) need to assign and store http connection context IDs and serve proxied requests based on that, will submit a PR later.

### PR DESCRIPTION
**Pull request by chaserhkj**
## Description

This PR adds `Connection: close` header to proxy mode responses such that clients are advised to close the connection after one single request, such that subsequent requests will be made by new connections and avoid triggering the 403 response from the reverse proxy server.

Also adds some missing commands for the E2E test makefile and the E2E regression test for the changes.

Fixes #268 

## Type of change
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes.

- [X] E2E regression test for reused connection requests. Run with `cd tests/e2e && make test T=11-reused-connection-requests`

## Checklist:
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes 
- [ ] A PR is open to update the helm chart (link)[https://github.com/KubeElasti/KubeElasti/tree/main/charts/elasti] if applicable
- [X] I have updated the [CHANGELOG.md](./CHANGELOG.md) file with the changes I made

### CODE REVIEW

File: resolver/internal/handler/handler.go [hunk 1]
```diff
@@ -137,6 +137,9 @@ func (h *Handler) handleAnyRequest(w http.ResponseWriter, req *http.Request) (*m
 	defer cancel()
 	if tryErr := h.throttler.Try(ctx, host,
 		func(count int) error {
+			// Advise client that the outstanding connection should be closed
+			// since routing change could potentially happen after this
+			w.Header().Set("Connection", "close")
```
Comment (ramantehlan) [inline resolver/internal/handler/handler.go:147]: @chaserhkj The issue is if scale up doesn't happen and we close the connection on every request, client will open a new connection for every request then.

Comment (chaserhkj) [reply resolver/internal/handler/handler.go:147]: How about we move this line after the `ProxyRequest` call, right before `DisableTrafficForHost` is being called for the host? `DisableTrafficForHost` would be the point where the routing through the proxy is guaranteed to stop so this might make more sense.

However I am not very sure if setting the header would work after the proxy handler returns. I need to test this out.

**Comment by chaserhkj** [comment]
E2E tests in CI are failing because I used a bash feature in the added part of the `send_traffic.sh` script but `/bin/sh` is not bash on ubuntu CI runners (it is in my local system). Changing shabang to `/bin/bash` and it should work in CI now

File: resolver/internal/handler/handler.go (hunk 1 above)
Comment (chaserhkj) [reply resolver/internal/handler/handler.go:147]: Ok I did a quick E2E test and it seems that we cannot move the header sets statements after the proxy handler function without breaking reused requests again. This makes sense since headers are written before the response body and setting headers after the body is already written probably would not do anything.

On the issue itself, I think the argument is that this is a performance trade-off we should be willing to take in exchange for correct behavior. The current implementation giving out 403s is just relying on the client side to retry and is very fault-intolerant. For example a simple `git clone` on a elasti-enabled git http server would just fail. And any CI workflows depending on this service would need a retry loop and becomes very impractical.

The other solution to this without `Connection: close` is to track each connection with a unique ID in its context, and store the first connection ID in the host struct such that the handler could look up and allow all requests from the same connection to go through even after the main traffic is switched. However this could have performance issues in another direction where a client opens a long-lived connection and every subsequent requests from the client needs to be proxied by the resolver.

Also, I think the only execution paths that are not leading to a scale up here (an execution path that `DisableTrafficForHost` is not called) are paths that return either 408 or 500 errors. Most http servers like apache or nginx would active close connections on these errors so I think it is ok to close the connection here anyways.

Comment (ramantehlan) [reply resolver/internal/handler/handler.go:147]: > The other solution to this without Connection: close is to track each connection with a unique ID in its context, and store the first connection ID in the host struct such that the handler could look up and allow all requests from the same connection to go through even after the main traffic is switched. However this could have performance issues in another direction where a client opens a long-lived connection and every subsequent requests from the client needs to be proxied by the resolver.

Right, performance issues and one more thing to take care of. We wouldn't want resolver to stay in the path. 


---

Got it, I think the changes makes sense. 2 suggested changes:

1. Should we also update the line 123, instead of `http.StatusForbidden`, using `StatusRequestTimeout`? 
2. This branch need a rebase, since we recently added support of auto probeResponse without scale-up, and the E2E tests added in this PR `[11-reused-connection-requests` conflicts new tests  [`11-probe-response`](https://github.com/KubeElasti/KubeElasti/tree/main/tests/e2e/tests/11-probe-response), though, both of them can start with `11-...` and run without a problem, but it just follows the convention we have.

**Review by ramantehlan — CHANGES_REQUESTED** [review]

**Comment by ramantehlan** [comment]
Thanks @chaserhkj for the PR! 
Just small changes requested, else looks good to be part of [v0.1.23](https://github.com/KubeElasti/KubeElasti/pull/270)

File: resolver/internal/handler/handler.go (hunk 1 above)
Comment (chaserhkj) [reply resolver/internal/handler/handler.go:147]: Done

**Comment by chaserhkj** [comment]
Done and rebased, PTAL

**Review by ramantehlan — APPROVED** [review]
LGTM
